config/routes.rb
Catarse::Application.routes.draw do
  mount RedactorRails::Engine => '/redactor_rails'
  mount JasmineRails::Engine => '/specs' if defined?(JasmineRails)
  devise_for(
    :users,
    {
      path: '',
      path_names:   { sign_in: :login, sign_out: :logout, sign_up: :sign_up },
      controllers:  { omniauth_callbacks: :omniauth_callbacks, passwords: :passwords, sessions: :sessions }
    }
  )

  devise_scope :user do
    post '/sign_up', {to: 'devise/registrations#create', as: :sign_up}
    get '/not-my-account', to: 'sessions#destroy_and_redirect', as: :not_my_account
  end

  # User permalink profile
  constraints SubdomainConstraint do
    get "/", to: 'users#show'
  end

  get '/amigos' => redirect('http://crowdfunding.catarse.me/amigos')
  get '/criadores' => redirect('http://crowdfunding.catarse.me/criadores')
  get '/paratodos' => redirect('http://crowdfunding.catarse.me/paratodos')

  get '/posts' => 'application#get_blog_posts'
  get '/project_edit' => 'application#redirect_to_last_edit'
  get '/billing_edit' => 'application#redirect_to_user_billing'
  get '/user_contributions' => 'application#redirect_to_user_contributions'
  post '/subscribe_newsletter' => 'application#subscribe_newsletter'

  get '/thank_you' => "static#thank_you"
  get '/follow-fb-friends' => "users#follow_fb_friends", as: :follow_fb_friends
  get '/connect-facebook' => "application#connect_facebook", as: :connect_fb

  get '/notifications/:notification_type/:notification_id' => 'notifications#show'

  filter :locale, exclude: /\/auth\//

  mount CatarsePagarme::Engine => "/", as: :catarse_pagarme
 #mount CatarseWepay::Engine => "/", as: :catarse_wepay
  mount Dbhero::Engine => "/dbhero", as: :dbhero

  resources :bank_accounts, except: [:destroy, :index] do
    member do
      get 'confirm'
      put 'request_refund'
    end
  end

  resources :categories, only: [] do
    member do
      get :subscribe, to: 'categories/subscriptions#create'
      get :unsubscribe, to: 'categories/subscriptions#destroy'
    end
  end
  resources :auto_complete_projects, only: [:index]
  resources :donations, only: [:create] do
    collection do
      get :confirm
    end
  end
  resources :auto_complete_cities, only: [:index]

  resources :projects, path: '/', only: [:index]
  resources :flexible_projects, path: '/', controller: 'projects', only: [:index]
  #@TODO update links, we don't need this anymore
  resources :flexible_projects, controller: 'projects', except: [:index]  do
    member do
      get :publish
      get :push_to_online
      get :validate_publish
      get :finish
    end
  end
  resources :projects, only: [ :create, :update, :edit, :new, :show] do
    resources :accounts, only: [:create, :update]
    resources :posts, controller: 'projects/posts', only: [ :destroy, :show, :create ]
    resources :rewards do
      post :sort, on: :member
    end
    resources :contributions, {except: [:index], controller: 'projects/contributions'} do
      collection do
        get :fallback_create, to: 'projects/contributions#create'
        put :update_status
      end
      member do
        get 'toggle_anonymous'
        get 'toggle_delivery'
        get :second_slip
        get :receipt
        get :no_account_refund
      end
      put :credits_checkout, on: :member
    end

    collection do
      get :fallback_create, to: 'projects#create'
    end
    get 'video', on: :collection
    member do
      get 'insights'
      get 'posts'
      get 'contributions_report'
      get 'download_reports'
      put 'pay'
      get 'embed'
      get 'video_embed'
      get 'embed_panel'
      get 'send_to_analysis'
      get 'publish'
      get 'validate_publish'
      get 'push_to_online'
    end
  end
  resources :users do
    resources :credit_cards, controller: 'users/credit_cards', only: [ :destroy ]
    member do
      #get :balance
      post :upload_image
      get :credit_cards
      get :unsubscribe_notifications
      get :credits
      get :settings
      get :billing
      get :reactivate
      post :new_password
    end

    resources :unsubscribes, only: [:create]
    member do
      get 'projects'
      put 'unsubscribe_update'
      put 'update_email'
      put 'update_password'
    end
  end

  get "/terms-of-use" => 'high_voltage/pages#show', id: 'terms_of_use'
  get "/privacy-policy" => 'high_voltage/pages#show', id: 'privacy_policy'
  get "/start" => 'high_voltage/pages#show', id: 'start'
  get "/jobs" => 'high_voltage/pages#show', id: 'jobs'
  get "/hello" => redirect("/start")
  get "/press" => 'high_voltage/pages#show', id: 'press'
  get "/assets" => 'high_voltage/pages#show', id: 'assets'
  get "/guides" => redirect("http://fazum.catarse.me/guia-financiamento-coletivo")
  get "/new-admin" => 'high_voltage/pages#show', id: 'new_admin'
  get "/explore" => 'high_voltage/pages#show', id: 'explore'
  get "/team" => 'high_voltage/pages#show', id: 'team'
  get '/flex' => redirect('http://crowdfunding.catarse.me')
  get "/projects_dashboard" => 'high_voltage/pages#show', id: 'projects_dashboard'


  # Root path should be after channel constraints
  root to: 'projects#index'

  namespace :reports do
    resources :contribution_reports_for_project_owners, only: [:index]
  end

  # Feedback form
  resources :feedbacks, only: [:create]

  namespace :admin do
    resources :projects, :flexible_projects, controller: 'projects', only: [ :index, :update, :destroy ] do
      member do
        put 'approve'
        put 'push_to_online'
        put 'reject'
        put 'push_to_draft'
        put 'push_to_trash'
      end
    end

    resources :financials, only: [ :index ]

    resources :contributions, only: [] do
      member do
        put 'gateway_refund'
      end
    end

    namespace :reports do
      resources :contribution_reports, only: [ :index ]
    end
  end

  resource :api_token, only: [:show]

  get "/:permalink" => "projects#show", as: :project_by_slug

end

app/models/concerns/project/all_or_nothing_state_validator.rb
# -*- coding: utf-8 -*-
# This module handles with default state validation
module Project::AllOrNothingStateValidator
  extend ActiveSupport::Concern

  included do
    with_options if: ->(x) { x.mode == 'aon' } do |wg| 
      # Start validations when project state
      # is included on ON_ONLINE_TO_END_STATE
      wg.with_options if: -> (x) { ( Project::ON_ONLINE_TO_END_STATES.include? x.state ) && ( x.mode == 'aon' ) } do |wo| 
        wo.validates_presence_of :goal, :online_days, :budget
        wo.validates_numericality_of :online_days, less_than_or_equal_to: 60, greater_than_or_equal_to: 1
      end
    end
  end
end

app/models/concerns/project/base_validator.rb
# -*- coding: utf-8 -*-
# This module handles with default project state validation
module Project::BaseValidator
  extend ActiveSupport::Concern

  included do
    ON_ONLINE_TO_END_STATES = %w(online successful waiting_funds failed).freeze

    # Validation for online? only state
    with_options if: :online? do |wo|
      wo.validates_presence_of :city
      wo.validates_length_of :name, maximum: Project::NAME_MAXLENGTH
    end

    # Start validations when project state
    # is included on ON_ONLINE_TO_END_STATE
    with_options if: -> (x) { ON_ONLINE_TO_END_STATES.include? x.state } do |wo| 
      wo.validates_presence_of :about_html, :headline, :goal

      wo.validates_presence_of :uploaded_image,
        unless: ->(project) { project.video_thumbnail.present? }

      wo.validate do
        [:uploaded_image, :about_html, :public_name].each do |attr|
          self.user.errors.add_on_blank(attr)
        end

        self.user.errors.each do |error, error_message|
          self.errors.add('user.' + error.to_s, error_message)
        end
      end

      wo.validates_presence_of :budget
      wo.validates_presence_of :account, message: 'Dados Bancários não podem ficar em branco'		

      wo.validates_numericality_of :online_days, less_than_or_equal_to: 365, greater_than_or_equal_to: 1, allow_nil: true

      wo.validate do
        if self.online_days.present? && self.rewards.any?(&:invalid_deliver_at?)
          self.errors['rewards.deliver_at'] << "Existe uma ou mais recompensas com o prazo de entrega menor que a data do fim do projeto"
        end
      end
      wo.validate do
        if self.account && (self.account.agency.try(:size) || 0) < 4
          self.errors['account.agency_size'] << "Agência deve ter pelo menos 4 dígitos"
        end
      end
    end
  end
end

app/models/concerns/project/custom_validators.rb
module Project::CustomValidators
  extend ActiveSupport::Concern

  included do
    @@routes = Rails.application.routes.routes
    validate :permalink_cant_be_route
    # This code might come back in a near future
    #validate :ensure_at_least_one_reward_validation, unless: :is_flexible?
    validate :validate_tags

    def validate_tags
      errors.add(:public_tags, :less_than_or_equal_to, count: 5) if public_tags.size > 5
    end

    def self.get_routes
      @@mapped_routes ||= @@routes.inject(Set.new) do |memo, item|
        memo << $1 if item.path.spec.to_s.match(/^\/([\w]+)\S/)
        memo
      end
    end

    def self.permalink_on_routes?(permalink)
      permalink && self.get_routes.include?(permalink.downcase)
    end

    def permalink_cant_be_route
      errors.add(:permalink, I18n.t("activerecord.errors.models.project.attributes.permalink.invalid")) if Project.permalink_on_routes?(permalink)
    end
    
    def ensure_at_least_one_reward_validation
      errors.add(
        'rewards.size',
        I18n.t("activerecord.errors.models.project.attributes.rewards.at_least_one")
      ) if rewards.empty?
    end
  end
end

app/models/concerns/project/error_groups.rb
module Project::ErrorGroups
  extend ActiveSupport::Concern

  included do
    begin
      ATTR_GROUPS = {
        basics: [:name, :permalink, :category_id, :city, :public_tags],
        goal: [:goal, :online_days],
        description: [:about_html],
        budget: [:budget],
        announce_expiration: [:online_days],
        card: [:uploaded_image, :headline],
        video: [:video_url],
        reward: [:'rewards.size', :'rewards.minimum_value', :'rewards.deliver_at'],
        user_about: [:'user.uploaded_image', :'user.public_name', :'user.about_html'],
        user_settings: ProjectAccount.attribute_names.map{|attr| ('account.' + attr).to_sym} << :'account.agency_size' << :account
      }
    rescue Exception => e
      puts "problem while using ErrorGroups concern:\n '#{e.message}'"
    end

    def error_included_on_group? error_attr, group_name
      Project::ATTR_GROUPS[group_name.to_sym].include?(error_attr)
    end

    def has_errors_for?(field)
      errors.include?(field)
    end

  end
end

app/models/concerns/project/video_handler.rb
module Project::VideoHandler
  extend ActiveSupport::Concern
  include Shared::VideoHandler

  included do
    mount_uploader :video_thumbnail, ProjectUploader

    def download_video_thumbnail
      self.video_thumbnail = open(self.video.thumbnail_large)  if self.video_valid?
      self.save
    rescue OpenURI::HTTPError, TypeError => e
      Rails.logger.info "-----> #{e.inspect}"
    end
  end
end

app/controllers/admin/projects_controller.rb
class Admin::ProjectsController < Admin::BaseController
  layout 'catarse_bootstrap'

  has_scope :by_user_email, :by_id, :pg_search, :user_name_contains, :with_state, :by_category_id, :order_by
  has_scope :between_created_at, :between_expires_at, :between_online_at, :between_updated_at, :goal_between, using: [ :start_at, :ends_at ]

  before_filter do
    @total_projects = Project.count(:all)
  end

  [:reject, :push_to_draft, :push_to_trash, :push_to_online].each do |name|
    define_method name do
      @project = Project.find params[:id]
      @project.send("#{name.to_s}")
      redirect_to :back
    end
  end

  def destroy
    @project = Project.find params[:id]
    if @project.can_push_to_trash?
      @project.push_to_trash
    end

    redirect_to admin_projects_path
  end

  def update
    resource.update_attributes(permitted_params)
    super
  end

  protected
  def permitted_params
    require_model = params.key?(:flexible_project) ? :flexible_project : :project
    params.require(require_model).permit(resource.attribute_names.map(&:to_sym))
  end

  def collection
    @scoped_projects = apply_scopes(Project).without_state('deleted')
    @projects = @scoped_projects.page(params[:page])
  end
end

app/controllers/projects/contributions_controller.rb
class Projects::ContributionsController < ApplicationController
  DEFAULT_AMOUNT = 10
  inherit_resources
  actions :index, :show, :new, :update, :review, :create
  skip_before_filter :verify_authenticity_token, only: [:moip]
  after_filter :verify_authorized, except: [:index]
  belongs_to :project
  before_filter :detect_old_browsers, only: [:new, :create]

  helper_method :engine

  def edit
    authorize resource
    if resource.reward.try(:sold_out?)
      flash[:alert] = t('.reward_sold_out')
      return redirect_to new_project_contribution_path(@project)
    end
    return render :existing_payment if resource.payments.exists?
  end

  def update
    authorize resource
    resource.update_attributes(permitted_params)
    resource.update_user_billing_info
    render json: {message: 'updated'}
  end

  def show
    authorize resource
    @title = t('projects.contributions.show.title')
  end

  def new
    @contribution = Contribution.new(project: parent, value: (params[:amount].presence || DEFAULT_AMOUNT).to_i)
    authorize @contribution

    @title = t('projects.contributions.new.title', name: @project.name)
    load_rewards

    if params[:reward_id] && (@selected_reward = @project.rewards.find params[:reward_id]) && !@selected_reward.sold_out?
      @contribution.reward = @selected_reward
      @contribution.value = "%0.0f" % @selected_reward.minimum_value
    end
  end

  def create
    @title = t('projects.contributions.create.title')
    @contribution = parent.contributions.new.localized
    @contribution.user = current_user
    @contribution.value = permitted_params[:value]
    @contribution.origin = Origin.process_hash(referral)
    @contribution.reward_id = (params[:contribution][:reward_id].to_i == 0 ? nil : params[:contribution][:reward_id])
    authorize @contribution
    @contribution.update_current_billing_info
    create! do |success,failure|
      failure.html do
        flash[:alert] = resource.errors.full_messages.to_sentence
        load_rewards
        render :new
      end
      success.html do
        flash[:notice] = nil
        session[:thank_you_contribution_id] = @contribution.id
        return redirect_to edit_project_contribution_path(project_id: @project.id, id: @contribution.id)
      end
    end
    @thank_you_id = @project.id
  end

  def no_account_refund
    authorize resource
  end

  def second_slip
    authorize resource
    if resource.reward.try(:sold_out?)
      flash[:alert] = t('.reward_sold_out')
      return redirect_to new_project_contribution_path(resource.project)
    end
    redirect_to resource.details.ordered.first.second_slip_path
  end

  def receipt
    authorize resource
    project = resource.project
    template = project.successful? ? 'contribution_project_successful' : 'confirm_contribution'
    render "user_notifier/mailer/#{template}", locals: { contribution: resource }, layout: 'layouts/email'
  end

  def toggle_delivery
    authorize resource
    if resource.delivery_status == 'received'
      resource.delivery_status = resource.reward_sent_at.nil? ? 'undelivered' : 'delivered'
      resource.reward_received_at = nil
    else
      resource.delivery_status = 'received'
      resource.reward_received_at = Time.current
    end
    resource.save!
    return render nothing: true
  end

  def update_status
    project = Project.find params['project_id']
    authorize project, :update?
    contributions = project.contributions.where(id: params['contributions'])
    contributions.update_all(delivery_status: params['delivery_status'])
    if params[:delivery_status] == 'delivered'
      contributions.update_all(reward_sent_at: Time.current)
    end

    respond_to do |format|
      format.json { render :json => { :success => 'OK' } }
    end
  end

  def toggle_anonymous
    authorize resource
    resource.toggle!(:anonymous)
    return render nothing: true
  end

  protected
  def load_rewards
    if @project.rewards.present?
      empty_reward = Reward.new(minimum_value: 0, description: t('projects.contributions.new.no_reward'))
      @rewards = [empty_reward] + @project.rewards.remaining.order(:minimum_value)
    else
      @rewards = []
    end
  end

  def permitted_params
    params.require(:contribution).permit(policy(resource).permitted_attributes)
  end

  def engine
    PaymentEngines.find_engine('Pagarme')
  end
end

app/controllers/projects/posts_controller.rb
class Projects::PostsController < ApplicationController
  respond_to :json, only: [:create]
  def parent
    @project ||= Project.find params[:project_id]
  end

  def show
    @post = parent.posts.find params[:id]
  end

  def create
    @post = ProjectPost.new
    @post.project_id = params[:project]
    @post.attributes = permitted_params
    authorize @post

    if @post.save
      respond_to do |format|
        format.json { render :json => { :success => 'OK' } }
      end
    end
  end

  def destroy
    authorize resource
    resource.destroy

    flash[:notice] = t('project.delete.posts')
    redirect_to posts_project_path(parent)
  end

  def resource
    @post ||= parent.posts.find params[:id]
  end

  def permitted_params
    params.require(:project_post).permit(policy(resource).permitted_attributes)
  end
end

app/views/catarse_bootstrap/projects/_aon_nav_actions.html.slim
- if @project.draft?
   = link_to validate_publish_project_path(@project), class: 'btn btn-medium' do
    = t('.publish')
    | &nbsp;&nbsp;
    span.fa.fa-chevron-right

app/views/catarse_bootstrap/projects/_aon_preview_explanation.html.slim
.u-text-center
  .w-container
    .w-row
      .w-col.w-col-8.w-col-push-2
        .fontweight-semibold.fontsize-large.u-margintop-40= t('projects.dashboard_preview.aon.header_subtitle') 
        p.fontsize-base= t('projects.dashboard_preview.aon.header_text') 
        .w-row.u-marginbottom-30
          .w-col.w-col-3
          .w-col.w-col-6
            input.w-input.text-field value="#{project_by_slug_url(@project.permalink, locale: '')}" type="text"
          .w-col.w-col-3
      .w-col.w-col-2

app/views/catarse_bootstrap/projects/_dashboard_announce_expiration.html.slim
#dashboard-announce_expiration-tab
  = simple_form_for @project, html: { class: 'project-form w-form', id: 'expiration-form' } do |form|
    .w-section
      .w-container
        .w-row.u-marginbottom-60
          .w-col.w-col-1
          .w-col.w-col-10
            = @project.display_errors(:announce_expiration)
            .card-big.card.card-terciary.u-radius
              .w-row.u-marginbottom-30
                .w-col.w-col-6._w-sub-col
                  .fontsize-small.u-marginbottom-10
                    | Em quantos dias, contados a partir de agora, você quer encerrar a sua arrecadação?
                    br
                .w-col.w-col-6
                  .w-row
                    .w-col.w-col-8.w-col-small-6.w-col-tiny-6
                      = form.input :online_days, as: :numeric, default: 2,
                        wrapper: :two_columns,
                        input_html: { class: 'positive medium', required: false, value: '2' },
                        validation_text: false, label: '', hint: ''
                    .w-col.w-col-4.w-col-small-6.w-col-tiny-6.text-field.postfix.no-hover.medium.prefix-permalink
                      .fontcolor-secondary.u-text-center.fontsize-base.lineheight-tightest Dias
              .fontcolor-secondary.u-text-center
                .fontsize-smaller Você poderá receber apoios até:
                .fontsize-base
                  span.expire-date=> l(2.days.from_now.to_date)
                  | as 23h59m
          .w-col.w-col-1
    .w-section
      .w-container
        .w-row
          .w-col.w-col-4
          .w-col.w-col-4
            a#show-modal.btn.btn-large.u-marginbottom-20   Confirmar

    .modal-backdrop.w-hidden
      .modal-dialog-outer
        .modal-dialog-inner.modal-dialog-small
          a.w-inline-block.modal-close.fa.fa-close.fa-lg  href="#announce_expiration"
          .modal-dialog-content
            .fontsize-large.u-text-center.u-marginbottom-30.fontweight-semibold Você confirma?
            .fontsize-large.u-text-center.u-marginbottom-30
              'Sua arrecadação irá terminar no dia 
              span.expire-date= l(2.days.from_now.to_date)
              |, as 23h59. Até lá, você pode captar recursos e seguir firme na sua campanha! Assim que o seu prazo chegar ao fim, você deverá confirmar os seus dados bancários. A partir de então, depositaremos o dinheiro na sua conta em até 10 dias úteis.
          .modal-dialog-nav-bottom
            .w-row
              .w-col.w-col-2
              .w-col.w-col-4
                = hidden_field_tag 'anchor', 'announce_expiration'
                = form.button :submit, 'Sim', class:'btn btn-large', id: 'budget-save'
              .w-col.w-col-4
                a#cancel.btn.btn-large.btn-terciary data-ix="modal-dialog-close" href="#announce_expiration"  Não
              .w-col.w-col-2

app/views/catarse_bootstrap/projects/_dashboard_nav.html.slim
- edit = defined?(edit_page) || false
= content_for :body_class, 'body-project open'
#project-nav
  .project-nav-wrapper
    nav.w-section.dashboard-nav.side
      = link_to (@project.published? ? project_by_slug_path(@project.permalink) : '#preview'), id: 'dashboard_preview_link', class: 'w-inline-block dashboard-project-name' , data: {target: '#dashboard_preview', tab_group: 'edit'} do
        - if @project.uploaded_image.present?
          img.thumb-project-dashboard src="#{@project.display_image(:project_thumb_large)}" width="114"
        - else
          img.thumb-project-dashboard src="#{image_path('thumb-project.png')}" width="114"
        .fontcolor-negative.lineheight-tight.fontsize-small= @project.name
        = image_tag("catarse_bootstrap/badge-#{@project.mode}-h.png", class: 'u-margintop-10', width: 80)

      #info-links
        = link_to insights_project_path(@project), class: 'dashboard-nav-link-left ' , id: 'dashboard_home_link', data: {tab_group: 'edit'} do
          span.fa.fa-bar-chart.fa-lg.fa-fw
          = t('.start_tab')
        - if @project.published?
          = link_to contributions_report_project_path(@project), class: 'dashboard-nav-link-left ' do
            span.fa.fa.fa-table.fa-lg.fa-fw
            = t('.reports_tab')
          = link_to posts_project_path(@project), class: 'dashboard-nav-link-left ' do
            span.fa.fa-bullhorn.fa-fw.fa-lg
            = t('.posts_tab')
            | &nbsp
            - if @project.posts.count > 0
              span.badge= @project.posts.count
            - else
              span.badge.badge-attention= 'Nenhuma'

      .edit-project-div
        - if @project.published? && !@project.is_flexible?
          button#toggle-edit-menu.dashboard-nav-link-left
            span.fa.fa-pencil.fa-fw.fa-lg
            = t('.edit_project')
          #edit-menu-items.w-hidden
            = render partial: 'dashboard_nav_links', locals: {edit: edit}
        - else
          = render partial: 'dashboard_nav_links', locals: {edit: edit}

          .btn-send-draft-fixed
            = render "#{@project.mode}_nav_actions"
  a.btn-dashboard href="#"
    span.fa.fa-bars.fa-lg

app/views/catarse_bootstrap/projects/_dashboard_nav_links.html.slim
-if @project.published?
  - link_class = 'dashboard-nav-link-left indent'
-else
  - link_class = 'dashboard-nav-link-left'
#dashboard-links
  - if !@project.published? || (current_user && current_user.admin?)
    = link_to (edit ? '#basics' : edit_project_path(@project, anchor: 'basics')), id: 'basics_link', class: link_class , data: {target: '#dashboard_basics', tab_group: 'edit'} do
      = @project.decorate.status_icon_for('basics', params[:action])
      = t(".#{@project.mode}.basics_tab")
    = link_to (edit ? '#goal' : edit_project_path(@project, anchor: 'goal')), id: 'goal_link', class: link_class , data: {target: '#dashboard_goal', tab_group: 'edit'} do
      = @project.decorate.status_icon_for('goal', params[:action])
      = t(".#{@project.mode}.goal_tab")

  = link_to (edit ? '#description' : edit_project_path(@project, anchor: 'description')), id: 'description_link', class: link_class , data: {target: '#dashboard_description', tab_group: 'edit'} do
    = @project.decorate.status_icon_for('description', params[:action])
    = t(".#{@project.mode}.description_tab")
  = link_to (edit ? '#video' : edit_project_path(@project, anchor: 'video')), id: 'dashboard_video_link', class: link_class , data: {target: '#dashboard_video', tab_group: 'edit'} do
    = @project.decorate.status_icon_for('video', params[:action])
    = t(".#{@project.mode}.video_tab").html_safe
  = link_to (edit ? '#budget' : edit_project_path(@project, anchor: 'budget')), id: 'budget_link', class: link_class , data: {target: '#dashboard_budget', tab_group: 'edit'} do
    = @project.decorate.status_icon_for('budget', params[:action])
    = t(".#{@project.mode}.budget_tab").html_safe
  = link_to (edit ? '#card' : edit_project_path(@project, anchor: 'card')), id: 'card_link', class: link_class , data: {target: '#dashboard_card', tab_group: 'edit'} do
    = @project.decorate.status_icon_for('card', params[:action])
    = t(".#{@project.mode}.card_tab")
  = link_to (edit ? '#reward' : edit_project_path(@project, anchor: 'reward')), id: 'dashboard_reward_link', class: link_class , data: {target: '#dashboard_reward', tab_group: 'edit'} do
    = @project.decorate.status_icon_for('reward', params[:action])
    = t(".#{@project.mode}.rewards_tab").html_safe
  = link_to (edit ? '#user_about' : edit_project_path(@project, anchor: 'user_about')), id: 'dashboard_user_about_link', class: link_class , data: {target: '#dashboard_user_about', tab_group: 'edit'} do
    = @project.decorate.status_icon_for('user_about', params[:action])
    = t(".#{@project.mode}.about_you_tab")
  = link_to '', '#analysis_success', data: {target: '#dashboard_analysis_success', tab_group: 'edit'}, class: 'w-hidden'

  - if @project.can_show_account_link? || (current_user && current_user.admin?)
    = link_to (edit ? '#user_settings' : edit_project_path(@project, anchor: 'user_settings')), id: 'dashboard_user_settings_link', class: ( link_class + ' u-marginbottom-20' ) , data: {target: '#dashboard_user_settings', tab_group: 'edit'} do
      = @project.decorate.status_icon_for('user_settings', params[:action])
      = t(".#{@project.mode}.account_tab")
  - if !@project.published? && @project.can_show_preview_link?
    = link_to (edit ? '#preview' : edit_project_path(@project, anchor: 'preview')), id: 'dashboard_preview_link', class: link_class , data: {target: '#dashboard_preview', tab_group: 'edit'} do
      span.fa.fa-fw.fa-eye.fa-lg>
      = t(".#{@project.mode}.preview_tab")

app/views/catarse_bootstrap/projects/_flex_preview_explanation.html.slim
- link_to_project = link_to(project_by_slug_url(@project.permalink, locale: ''), project_by_slug_url(@project.permalink, locale: ''))
.u-text-center
  .w-container
    .w-row
      .w-col.w-col-8.w-col-push-2
        .fontweight-semibold.fontsize-large.u-margintop-40= t('projects.dashboard_preview.flex.header_subtitle') 
        p.fontsize-base= t('projects.dashboard_preview.flex.header_text', link: link_to_project).html_safe 
        .w-row.u-marginbottom-30
          .w-col.w-col-3
          .w-col.w-col-6
            = link_to t('projects.dashboard_preview.flex.publish_btn_html'), publish_flexible_project_path(@project), class: 'w-button btn btn-large'
          .w-col.w-col-3
          .w-col.w-col-2

app/views/catarse_bootstrap/projects/_project_header.html.slim
.w-section.section-product[class=@project.mode]
#project-header.page-header.u-text-center[data-stats=@project.to_analytics_json]
  .w-container
    h1.fontsize-larger.fontweight-semibold.project-name[itemprop="name"] = @project.name
    h2.fontsize-base.lineheight-looser[itemprop="author"]
      = t('projects.index.box.by')
      |&nbsp;
      = @project.user.display_name