config/routes.rb
Catarse::Application.routes.draw do
  mount RedactorRails::Engine => '/redactor_rails'
  mount JasmineRails::Engine => '/specs' if defined?(JasmineRails)
  devise_for(
    :users,
    {
      path: '',
      path_names:   { sign_in: :login, sign_out: :logout, sign_up: :sign_up },
      controllers:  { omniauth_callbacks: :omniauth_callbacks, passwords: :passwords, sessions: :sessions }
    }
  )

  devise_scope :user do
    post '/sign_up', {to: 'devise/registrations#create', as: :sign_up}
    get '/not-my-account', to: 'sessions#destroy_and_redirect', as: :not_my_account
  end

  # User permalink profile
  constraints SubdomainConstraint do
    get "/", to: 'users#show'
  end

  get '/amigos' => redirect('http://crowdfunding.catarse.me/amigos')
  get '/criadores' => redirect('http://crowdfunding.catarse.me/criadores')
  get '/paratodos' => redirect('http://crowdfunding.catarse.me/paratodos')

  get '/posts' => 'application#get_blog_posts'
  get '/project_edit' => 'application#redirect_to_last_edit'
  get '/billing_edit' => 'application#redirect_to_user_billing'
  get '/user_contributions' => 'application#redirect_to_user_contributions'
  post '/subscribe_newsletter' => 'application#subscribe_newsletter'

  get '/thank_you' => "static#thank_you"
  get '/follow-fb-friends' => "users#follow_fb_friends", as: :follow_fb_friends
  get '/connect-facebook' => "application#connect_facebook", as: :connect_fb

  get '/notifications/:notification_type/:notification_id' => 'notifications#show'

  filter :locale, exclude: /\/auth\//

  mount CatarsePagarme::Engine => "/", as: :catarse_pagarme
 #mount CatarseWepay::Engine => "/", as: :catarse_wepay
  mount Dbhero::Engine => "/dbhero", as: :dbhero

  resources :bank_accounts, except: [:destroy, :index] do
    member do
      get 'confirm'
      put 'request_refund'
    end
  end

  resources :categories, only: [] do
    member do
      get :subscribe, to: 'categories/subscriptions#create'
      get :unsubscribe, to: 'categories/subscriptions#destroy'
    end
  end
  resources :auto_complete_projects, only: [:index]
  resources :donations, only: [:create] do
    collection do
      get :confirm
    end
  end
  resources :auto_complete_cities, only: [:index]

  resources :projects, path: '/', only: [:index]
  resources :flexible_projects, path: '/', controller: 'projects', only: [:index]
  #@TODO update links, we don't need this anymore
  resources :flexible_projects, controller: 'projects', except: [:index]  do
    member do
      get :publish
      get :push_to_online
      get :validate_publish
      get :finish
    end
  end
  resources :projects, only: [ :create, :update, :edit, :new, :show] do
    resources :accounts, only: [:create, :update]
    resources :posts, controller: 'projects/posts', only: [ :destroy, :show, :create ]
    resources :rewards do
      post :sort, on: :member
    end
    resources :contributions, {except: [:index], controller: 'projects/contributions'} do
      collection do
        get :fallback_create, to: 'projects/contributions#create'
        put :update_status
      end
      member do
        get 'toggle_anonymous'
        get 'toggle_delivery'
        get :second_slip
        get :receipt
        get :no_account_refund
      end
      put :credits_checkout, on: :member
    end

    collection do
      get :fallback_create, to: 'projects#create'
    end
    get 'video', on: :collection
    member do
      get 'insights'
      get 'posts'
      get 'contributions_report'
      get 'download_reports'
      put 'pay'
      get 'embed'
      get 'video_embed'
      get 'embed_panel'
      get 'send_to_analysis'
      get 'publish'
      get 'validate_publish'
      get 'push_to_online'
    end
  end
  resources :users do
    resources :credit_cards, controller: 'users/credit_cards', only: [ :destroy ]
    member do
      #get :balance
      post :upload_image
      get :credit_cards
      get :unsubscribe_notifications
      get :credits
      get :settings
      get :billing
      get :reactivate
      post :new_password
    end

    resources :unsubscribes, only: [:create]
    member do
      get 'projects'
      put 'unsubscribe_update'
      put 'update_email'
      put 'update_password'
    end
  end

  get "/terms-of-use" => 'high_voltage/pages#show', id: 'terms_of_use'
  get "/privacy-policy" => 'high_voltage/pages#show', id: 'privacy_policy'
  get "/start" => 'high_voltage/pages#show', id: 'start'
  get "/jobs" => 'high_voltage/pages#show', id: 'jobs'
  get "/hello" => redirect("/start")
  get "/press" => 'high_voltage/pages#show', id: 'press'
  get "/assets" => 'high_voltage/pages#show', id: 'assets'
  get "/guides" => redirect("http://fazum.catarse.me/guia-financiamento-coletivo")
  get "/new-admin" => 'high_voltage/pages#show', id: 'new_admin'
  get "/explore" => 'high_voltage/pages#show', id: 'explore'
  get "/team" => 'high_voltage/pages#show', id: 'team'
  get '/flex' => redirect('http://crowdfunding.catarse.me')
  get "/projects_dashboard" => 'high_voltage/pages#show', id: 'projects_dashboard'


  # Root path should be after channel constraints
  root to: 'projects#index'

  namespace :reports do
    resources :contribution_reports_for_project_owners, only: [:index]
  end

  # Feedback form
  resources :feedbacks, only: [:create]

  namespace :admin do
    resources :projects, :flexible_projects, controller: 'projects', only: [ :index, :update, :destroy ] do
      member do
        put 'approve'
        put 'push_to_online'
        put 'reject'
        put 'push_to_draft'
        put 'push_to_trash'
      end
    end

    resources :financials, only: [ :index ]

    resources :contributions, only: [] do
      member do
        put 'gateway_refund'
      end
    end

    namespace :reports do
      resources :contribution_reports, only: [ :index ]
    end
  end

  resource :api_token, only: [:show]

  get "/:permalink" => "projects#show", as: :project_by_slug

end

app/models/concerns/contribution/custom_validators.rb
module Contribution::CustomValidators
  extend ActiveSupport::Concern

  included do
    validate :reward_must_be_from_project
    validate :value_must_be_at_least_rewards_value
    validate :should_not_contribute_if_maximum_contributions_been_reached, on: :create

    def reward_must_be_from_project
      return unless reward
      errors.add(:reward, I18n.t('contribution.reward_must_be_from_project')) unless reward.project == project
    end

    def value_must_be_at_least_rewards_value
      return unless reward
      errors.add(:value, I18n.t('contribution.value_must_be_at_least_rewards_value', minimum_value: reward.display_minimum)) unless value.to_f >= reward.minimum_value
    end

    def should_not_contribute_if_maximum_contributions_been_reached
      return unless reward && reward.maximum_contributions && reward.maximum_contributions > 0
      errors.add(:reward, I18n.t('contribution.should_not_contribute_if_maximum_contributions_been_reached')) if reward.sold_out?
    end
  end
end

app/models/concerns/contribution/state_machine_handler.rb
module Contribution::StateMachineHandler
  extend ActiveSupport::Concern

  included do
    state_machine :state, initial: :pending do
      state :pending, value: 'pending'
      state :waiting_confirmation, value: 'waiting_confirmation'
      state :confirmed, value: 'confirmed'
      state :canceled, value: 'canceled'
      state :refunded, value: 'refunded'
      state :requested_refund, value: 'requested_refund'
      state :chargeback, value: 'chargeback'
      state :refunded_and_canceled, value: 'refunded_and_canceled'
      state :deleted, value: 'deleted'
      state :invalid_payment, value: 'invalid_payment'

      event :push_to_trash do
        transition all => :deleted
      end

      event :pendent do
        transition all => :pending
      end

      event :waiting do
        transition pending: :waiting_confirmation
      end

      event :invalid do
        transition all => :invalid_payment
      end

      event :confirm do
        transition [:pending, :confirmed, :waiting_confirmation, :canceled, :deleted] => :confirmed
      end

      event :cancel do
        transition all => :canceled
      end

      event :request_refund do
        transition confirmed: :requested_refund, if: ->(contribution){
          contribution.user.credits >= contribution.value && !contribution.credits
        }
      end

      event :refund do
        transition [:requested_refund, :confirmed] => :refunded
      end

      event :hide do
        transition all => :refunded_and_canceled
      end

      after_transition do |contribution, transition|
        contribution.notify_observers :"from_#{transition.from}_to_#{transition.to}"

        to_column = "#{transition.to}_at".to_sym
        if contribution.has_attribute?(to_column)
          contribution.update_attribute to_column, DateTime.current
        end
      end

      after_transition any => [:refunded_and_canceled] do |contribution, transition|
        contribution.notify_to_contributor :refunded_and_canceled
      end
    end
  end
end

app/models/concerns/project/all_or_nothing_state_validator.rb
# -*- coding: utf-8 -*-
# This module handles with default state validation
module Project::AllOrNothingStateValidator
  extend ActiveSupport::Concern

  included do
    with_options if: ->(x) { x.mode == 'aon' } do |wg| 
      # Start validations when project state
      # is included on ON_ONLINE_TO_END_STATE
      wg.with_options if: -> (x) { ( Project::ON_ONLINE_TO_END_STATES.include? x.state ) && ( x.mode == 'aon' ) } do |wo| 
        wo.validates_presence_of :goal, :online_days, :budget
        wo.validates_numericality_of :online_days, less_than_or_equal_to: 60, greater_than_or_equal_to: 1
      end
    end
  end
end

app/models/concerns/project/video_handler.rb
module Project::VideoHandler
  extend ActiveSupport::Concern
  include Shared::VideoHandler

  included do
    mount_uploader :video_thumbnail, ProjectUploader

    def download_video_thumbnail
      self.video_thumbnail = open(self.video.thumbnail_large)  if self.video_valid?
      self.save
    rescue OpenURI::HTTPError, TypeError => e
      Rails.logger.info "-----> #{e.inspect}"
    end
  end
end

app/controllers/admin/contributions_controller.rb
class Admin::ContributionsController < Admin::BaseController
  layout 'catarse_bootstrap'

  # gateway_refund is used as external action in catarse.js
  def gateway_refund
    resource.direct_refund
    respond_to do |format|
      format.html do
        return redirect_to admin_contributions_path(params[:local_params])
      end
      format.json do
        return render json: []
      end
    end

  end

  protected
  def resource
    ContributionDetail.find_by_id params[:id]
  end
end

app/controllers/admin/projects_controller.rb
class Admin::ProjectsController < Admin::BaseController
  layout 'catarse_bootstrap'

  has_scope :by_user_email, :by_id, :pg_search, :user_name_contains, :with_state, :by_category_id, :order_by
  has_scope :between_created_at, :between_expires_at, :between_online_at, :between_updated_at, :goal_between, using: [ :start_at, :ends_at ]

  before_filter do
    @total_projects = Project.count(:all)
  end

  [:reject, :push_to_draft, :push_to_trash, :push_to_online].each do |name|
    define_method name do
      @project = Project.find params[:id]
      @project.send("#{name.to_s}")
      redirect_to :back
    end
  end

  def destroy
    @project = Project.find params[:id]
    if @project.can_push_to_trash?
      @project.push_to_trash
    end

    redirect_to admin_projects_path
  end

  def update
    resource.update_attributes(permitted_params)
    super
  end

  protected
  def permitted_params
    require_model = params.key?(:flexible_project) ? :flexible_project : :project
    params.require(require_model).permit(resource.attribute_names.map(&:to_sym))
  end

  def collection
    @scoped_projects = apply_scopes(Project).without_state('deleted')
    @projects = @scoped_projects.page(params[:page])
  end
end

app/controllers/projects/contributions_controller.rb
class Projects::ContributionsController < ApplicationController
  DEFAULT_AMOUNT = 10
  inherit_resources
  actions :index, :show, :new, :update, :review, :create
  skip_before_filter :verify_authenticity_token, only: [:moip]
  after_filter :verify_authorized, except: [:index]
  belongs_to :project
  before_filter :detect_old_browsers, only: [:new, :create]

  helper_method :engine

  def edit
    authorize resource
    if resource.reward.try(:sold_out?)
      flash[:alert] = t('.reward_sold_out')
      return redirect_to new_project_contribution_path(@project)
    end
    return render :existing_payment if resource.payments.exists?
  end

  def update
    authorize resource
    resource.update_attributes(permitted_params)
    resource.update_user_billing_info
    render json: {message: 'updated'}
  end

  def show
    authorize resource
    @title = t('projects.contributions.show.title')
  end

  def new
    @contribution = Contribution.new(project: parent, value: (params[:amount].presence || DEFAULT_AMOUNT).to_i)
    authorize @contribution

    @title = t('projects.contributions.new.title', name: @project.name)
    load_rewards

    if params[:reward_id] && (@selected_reward = @project.rewards.find params[:reward_id]) && !@selected_reward.sold_out?
      @contribution.reward = @selected_reward
      @contribution.value = "%0.0f" % @selected_reward.minimum_value
    end
  end

  def create
    @title = t('projects.contributions.create.title')
    @contribution = parent.contributions.new.localized
    @contribution.user = current_user
    @contribution.value = permitted_params[:value]
    @contribution.origin = Origin.process_hash(referral)
    @contribution.reward_id = (params[:contribution][:reward_id].to_i == 0 ? nil : params[:contribution][:reward_id])
    authorize @contribution
    @contribution.update_current_billing_info
    create! do |success,failure|
      failure.html do
        flash[:alert] = resource.errors.full_messages.to_sentence
        load_rewards
        render :new
      end
      success.html do
        flash[:notice] = nil
        session[:thank_you_contribution_id] = @contribution.id
        return redirect_to edit_project_contribution_path(project_id: @project.id, id: @contribution.id)
      end
    end
    @thank_you_id = @project.id
  end

  def no_account_refund
    authorize resource
  end

  def second_slip
    authorize resource
    if resource.reward.try(:sold_out?)
      flash[:alert] = t('.reward_sold_out')
      return redirect_to new_project_contribution_path(resource.project)
    end
    redirect_to resource.details.ordered.first.second_slip_path
  end

  def receipt
    authorize resource
    project = resource.project
    template = project.successful? ? 'contribution_project_successful' : 'confirm_contribution'
    render "user_notifier/mailer/#{template}", locals: { contribution: resource }, layout: 'layouts/email'
  end

  def toggle_delivery
    authorize resource
    if resource.delivery_status == 'received'
      resource.delivery_status = resource.reward_sent_at.nil? ? 'undelivered' : 'delivered'
      resource.reward_received_at = nil
    else
      resource.delivery_status = 'received'
      resource.reward_received_at = Time.current
    end
    resource.save!
    return render nothing: true
  end

  def update_status
    project = Project.find params['project_id']
    authorize project, :update?
    contributions = project.contributions.where(id: params['contributions'])
    contributions.update_all(delivery_status: params['delivery_status'])
    if params[:delivery_status] == 'delivered'
      contributions.update_all(reward_sent_at: Time.current)
    end

    respond_to do |format|
      format.json { render :json => { :success => 'OK' } }
    end
  end

  def toggle_anonymous
    authorize resource
    resource.toggle!(:anonymous)
    return render nothing: true
  end

  protected
  def load_rewards
    if @project.rewards.present?
      empty_reward = Reward.new(minimum_value: 0, description: t('projects.contributions.new.no_reward'))
      @rewards = [empty_reward] + @project.rewards.remaining.order(:minimum_value)
    else
      @rewards = []
    end
  end

  def permitted_params
    params.require(:contribution).permit(policy(resource).permitted_attributes)
  end

  def engine
    PaymentEngines.find_engine('Pagarme')
  end
end

app/controllers/projects/posts_controller.rb
class Projects::PostsController < ApplicationController
  respond_to :json, only: [:create]
  def parent
    @project ||= Project.find params[:project_id]
  end

  def show
    @post = parent.posts.find params[:id]
  end

  def create
    @post = ProjectPost.new
    @post.project_id = params[:project]
    @post.attributes = permitted_params
    authorize @post

    if @post.save
      respond_to do |format|
        format.json { render :json => { :success => 'OK' } }
      end
    end
  end

  def destroy
    authorize resource
    resource.destroy

    flash[:notice] = t('project.delete.posts')
    redirect_to posts_project_path(parent)
  end

  def resource
    @post ||= parent.posts.find params[:id]
  end

  def permitted_params
    params.require(:project_post).permit(policy(resource).permitted_attributes)
  end
end

app/views/catarse_bootstrap/projects/contributions/_aon_faq_box.html.slim
#faq-box.w-hidden-small.w-hidden-tiny.back-faq-box data-ix="new-interaction"
  .w-row.u-marginbottom-30
    .w-col.w-col-2.w-col-small-2.w-col-tiny-2
      img src="https://daks2k3a4ib2z.cloudfront.net/54b440b85608e3f4389db387/5632d273ec8a367d341b4999_badge-aon.png" width="30" /
    .w-col.w-col-10.w-col-small-10.w-col-tiny-10
      .w-inline-block.fontsize-smallest._w-inline-block.fontcolor-secondary=t('projects.contributions.faq.all_or_nothing.explanation')

  .u-marginbottom-20.fontsize-small.fontweight-semibold=t('projects.contributions.faq.all_or_nothing.common_questions')
  ul.w-list-unstyled
    li.list-question.fontsize-smaller.alt-link  #{t('projects.contributions.faq.all_or_nothing.how_contribute')}
    li.list-answer.u-marginbottom-20.fontsize-smaller=t('projects.contributions.faq.all_or_nothing.how_contribute_answer')

    li.list-question.fontsize-smaller.alt-link  #{t('projects.contributions.faq.all_or_nothing.when_made_payment')}
    li.list-answer.u-marginbottom-20.fontsize-smaller=t('projects.contributions.faq.all_or_nothing.when_made_payment_answer')

    li.list-question.fontsize-smaller.alt-link  #{t('projects.contributions.faq.all_or_nothing.when_about_my_payment_data')}
    li.list-answer.u-marginbottom-20.fontsize-smaller=t('projects.contributions.faq.all_or_nothing.when_about_my_payment_data_answer')

    li.list-question.fontsize-smaller.alt-link  #{t('projects.contributions.faq.all_or_nothing.when_project_fails')}
    li.list-answer.u-marginbottom-20.fontsize-smaller=t('projects.contributions.faq.all_or_nothing.when_project_fails_answer')

    li.list-question.fontsize-smaller.alt-link  #{t('projects.contributions.faq.all_or_nothing.when_project_funded')}
    li.list-answer.u-marginbottom-20.fontsize-smaller=raw t('projects.contributions.faq.all_or_nothing.when_project_funded_answer', name: link_to(@project.user.display_name, user_path(@project.user), target: '_blank'))

app/views/catarse_bootstrap/projects/contributions/_selected_reward.html.slim
.card.u-radius.u-marginbottom-20
  .fontsize-smaller.fontweight-semibold.u-marginbottom-20 = t('.value')
  .w-clearfix.u-marginbottom-20
    .fontsize-larger.text-success.u-left = number_to_currency @contribution.localized.value
    = link_to t('.edit'), new_project_contribution_path(@contribution.project), class: 'fontsize-small link-hidden u-right fontweight-semibold'
  - if @project.rewards.present?
    .back-payment-info-reward
      .fontsize-smaller.fontweight-semibold.u-marginbottom-10 = t('.reward')
      .fontsize-smallest
        - if @contribution.reward
          == @contribution.reward.display_description
        - else
          == t('.review_without_reward_html', value: (number_to_currency @contribution.localized.value))

app/views/catarse_bootstrap/projects/contributions/_thank_you.html.slim
#project-header.u-marginbottom-30.page-header[data-stats=@project.to_analytics_json]
  .w-container
    .w-row
      .w-col.w-col-8.w-col-push-2
        .u-text-center.u-marginbottom-20
          = image_tag @project.user.decorate.display_image, class: 'u-round thumb big', alt: @project.user.decorate.display_name
        .u-text-center
          .fontsize-larger.text-success.u-marginbottom-20 = t('.thank_you') 
          .fontsize-base.u-marginbottom-40
            = t('.thank_you_text_html', total: @project.total_contributions, email: @contribution.user.email,  link2: (link_to t('.profile_link'), edit_user_path(resource.user, anchor: 'contributions'), class: 'alt-link'))
          .fontsize-base.fontweight-semibold.u-marginbottom-20 = t('.share_back')
        .w-row.u-marginbottom-20
          .w-col.w-col-6.w-col-small-6.w-col-tiny-6.w-sub-col-middle
            div
              img.icon-share-mobile alt="53a3f66e05eb6144171d8edb_facebook-xxl.png" src="http://uploads.webflow.com/54b440b85608e3f4389db387/53a3f66e05eb6144171d8edb_facebook-xxl.png" /
              = link_to "http://www.facebook.com/share.php?u=#{url_encode(project_by_slug_url(@project.permalink, {ref: 'ctrse_thankyou',utm_source:'facebook.com',utm_medium:'social',utm_campaign:'thanks_share'}))}", target: :_blank, id: 'facebook_share', data: { title: @project.name }, class: 'btn btn-medium btn-fb' do
                = t('.share')
          .w-col.w-col-6.w-col-small-6.w-col-tiny-6
            div
              img.icon-share-mobile alt="53a3f65105eb6144171d8eda_twitter-256.png" src="http://uploads.webflow.com/54b440b85608e3f4389db387/53a3f65105eb6144171d8eda_twitter-256.png" /
              /a.btn.btn-medium.btn-tweet href="#"  Tweet
              = link_to "http://twitter.com/?status=#{url_encode(t('i_just_contributed', name: @project.name)+' '+project_by_slug_url(@project.permalink, {ref: 'ctrse_thankyou',utm_source:'twitter.com',utm_medium:'social',utm_campaign:'thanks_share'}))}", target: :_blank, id: "twitter_share_button", data: { title: @project.name }, class: 'btn btn-medium btn-tweet' do
                = t('.tweet')

- if @contribution.recommended_projects.exists?
  .section.u-marginbottom-40
    .w-container
      .u-marginbottom-20.fontweight-semibold.fontsize-base.u-text-center= t('.project_recommendations') 
      .w-row
        == render_projects @contribution.recommended_projects.limit(3), 'ctrse_thankyou_r', { wrapper_class: 'w-col w-col-4' }
- content_for :js_after do
  javascript:
    $(window).ready(function(){
      CatarseAnalytics.event({cat:'contribution_finish',act:'contribution_finished',lbl:'creditcard',val:#{@contribution.value},extraData:{contribution_id:#{@contribution.id}}});
      CatarseAnalytics.checkout('#{@contribution.id}','[#{@project.permalink}] #{(@contribution.reward.try(:minimum_value) || 0)} [creditcard]','#{@contribution.reward_id}','#{@project.category}','#{@contribution.value}','#{@contribution.value*@contribution.project.service_fee}');
    });

app/views/catarse_bootstrap/projects/contributions/edit.html.slim
- content_for :title, t('.page-title', name: @project.name)
- content_for :tracker_snippet_html do
  == @project.tracker_snippet_html

#application[data-parameters=@project.to_js_json(current_user) data-contribution=@contribution.to_json data-stats=@project.to_analytics_json]

- content_for :application_js do
  = javascript_include_tag "api/application"

app/views/catarse_bootstrap/projects/contributions/no_account_refund.html.slim
= render 'shared/header'
- can_donate = resource.user.pending_refund_payments.present?

#contribution-donation
  .w-section.section-one-column.u-margintop-40
    .w-container
      .w-row.u-text-center.u-marginbottom-60
        .w-col.w-col-2
        .w-col.w-col-8
          .fontsize-larger.u-marginbottom-20 Decida o que fazer com o seu dinheiro no #{CatarseSettings[:company_name]}!

          .fontsize-base= t('.fill_form_text', \
            amount: resource.user.decorator.display_pending_refund_payments_amount)
        .w-col.w-col-2
      .w-row
        - if can_donate
          .w-col.w-col-6
            .card.medium.card-terciary.u-radius
              = link_to 'Quero doar para o Catarse!', confirm_donations_path, class: 'w-button btn btn-large u-marginbottom-30', method: 'get'
              .fontsize-small ihaaa! Seu dinheiro será utilizado para financiar operações do Catarse e um monte de inovações que vem por aí em 2016. São novidades que certamente ajudarão muita gente. Sinta-se parte do time e ajude a espalhar o financiamento coletivo no Brasil!
        .w-col.w-col-6 class="#{can_donate ? '' : 'w-col-push-3'}"
          .card.medium.card-terciary.u-radius.u-marginbottom-20
            = link_to 'Quero meu dinheiro de volta!', new_bank_account_path, class: 'w-button btn btn-large u-marginbottom-30'
            .fontsize-small Seu dinheiro será depositado integralmente em sua conta bancária em até 5 dias úteis. Para que possamos efetuar essa transferência, basta nos informar seus dados bancários. Nenhuma taxa é cobrada nesta operação, fique tranquilo!
  .w-section.section.divider.bg-gray.before-footer
    .w-container
      .fontsize-large.u-text-center.fontweight-semibold.u-marginbottom-30 Dúvidas frequentes
      .w-row.u-marginbottom-60
        .w-col.w-col-6
          .card.u-marginbottom-20.u-radius.btn-terciary.show-answer-faq
            .fontsize-base Porque tenho dinheiro no Catarse?
            p.fontsize-small.box-slider.closed   Em algum momento nos últimos 5 anos você apoiou projetos de crowdfunding / financiamento coletivo no Catarse que, infelizmente, não atingiram a meta. Como utilizamos o sistema tudo-ou-nada, se o projeto não bate a meta todos têm direito a receber o dinheiro apoiado de volta. Algumas pessoas não receberam essas devoluções, seja porque o cartão utilizado estava bloqueado no momento da devolução, ou porque não preencheram os dados bancários para realizarmos a devolução.
          .card.u-marginbottom-20.u-radius.btn-terciary.show-answer-faq
            .fontsize-base O que acontece se eu não tomar essa decisão?
            p.fontsize-small.box-slider.closed   No dia 11 de julho de 2015 realizamos uma alteração em nossos Termos de Uso que prevê que caso não consigamos entrar em contato com você por meio dos dados de cadastro registrados na nossa plataforma e nos falte alguma informação bancária para realizar o reembolso, dentro do período de 12 meses a contar da data de encerramento do projeto os valores serão considerados renunciados e poderão ser utilizados pelo CATARSE para reinvestir na plataforma e beneficiar a comunidade. Se você não decidir após 30 dias do envio da primeira notificação, os valores em crédito serão considerados renunciados.
        .w-col.w-col-6
          .card.u-marginbottom-20.u-radius.btn-terciary.show-answer-faq
            .fontsize-base Porque tenho que tomar essa decisão em até 30 dias?
            p.fontsize-small.box-slider.closed   Definimos o prazo de 30 dias a partir da primeira notificação para termos a certeza de que você vai ver essa mensagem e tomar essa decisão. Pense com bastante amor e carinho! Precisamos da sua resposta para que possamos fazer um planejamento financeiro mais preciso e transparente.
          .card.u-marginbottom-20.u-radius.btn-terciary.show-answer-faq
            .fontsize-base Posso usar meus créditos para apoiar outro projeto?
            p.fontsize-small.box-slider.closed Desde o dia 10/11/2014 não é mais possível utilizar os créditos no Catarse para apoiar os projetos na plataforma. Essa é uma das mudanças que fizemos para simplificar o processo de pagamentos e garantir os reembolsos para todo mundo. Clicando em "Quero doar para o Catarse" você apoiará diretamente as operações da plataforma, ajudando-nos a espalhar ainda mais o financiamento coletivo pelo Brasil.
  = render 'shared/footer'

app/views/catarse_bootstrap/projects/contributions/show.html.slim
- content_for :tracker_snippet_html do
  == @project.tracker_snippet_html

#application[data-contribution=@contribution.contribution_json data-stats=@project.to_analytics_json]

- content_for :application_js do
  = javascript_include_tag "api/application"